# Generated by Django 2.2.3 on 2019-09-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upilink',
            name='json_data',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
